def config = readYaml text: "${env.PIPELINE_CONFIG}"

  stages {
    stage("run run ANYTHING") {
      steps {
        echo "What to run: ${config.run_me}"
        // sh "${config.run_me}"
      }
    }
  }
